force-app/main/default/objects/ATAK_Project__c/ATAK_Project__c.object-meta.xml
<CustomObject>
    <label>ATAK Project</label>
    <nameField>
        <label>ATAK Projects Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ATAK Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ATAK_Project__c/fields/ATAK_Creation_Date__c.field-meta.xml
<CustomField>
    <fullName>ATAK_Creation_Date__c</fullName>
    <label>ATAK Creation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ATAK_Project__c/fields/Cost_centre_Atak_Id__c.field-meta.xml
<CustomField>
    <fullName>Cost_centre_Atak_Id__c</fullName>
    <label>Cost Centre ATAK Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATAK_Project__c/fields/Cost_centre_Atak_Name__c.field-meta.xml
<CustomField>
    <fullName>Cost_centre_Atak_Name__c</fullName>
    <label>Cost centre Atak Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATAK_Project__c/fields/Department_Name__c.field-meta.xml
<CustomField>
    <fullName>Department_Name__c</fullName>
    <label>Department Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATAK_Project__c/fields/Depot__c.field-meta.xml
<CustomField>
    <fullName>Depot__c</fullName>
    <label>Depot</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATAK_Project__c/fields/Discipline__c.field-meta.xml
<CustomField>
    <fullName>Discipline__c</fullName>
    <label>Discipline</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATAK_Project__c/fields/Dossier__c.field-meta.xml
<CustomField>
    <fullName>Dossier__c</fullName>
    <label>Dossier</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATAK_Project__c/fields/Site_Manager_Code__c.field-meta.xml
<CustomField>
    <fullName>Site_Manager_Code__c</fullName>
    <label>Site Manager Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATAK_Project__c/fields/SubProject_ATAK__c.field-meta.xml
<CustomField>
    <fullName>SubProject_ATAK__c</fullName>
    <externalId>true</externalId>
    <label>Subproject ATAK</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ATAK_Project__c/fields/Subproject_Name__c.field-meta.xml
<CustomField>
    <fullName>Subproject_Name__c</fullName>
    <description>filled via a flow accoridng to a naming convention</description>
    <label>Subproject Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/ATAK_Code__c.field-meta.xml
<CustomField>
    <fullName>ATAK_Code__c</fullName>
    <externalId>true</externalId>
    <label>ATAK Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ATAKProjectService.cls
/**
 * Created by fpardon on 05/11/2024.
 */

public with sharing class ATAKProjectService {

    public static String createATAKProjects(ATAKProjectWrapper projects) {
        System.debug('ATAKProjectService.createATAKProject');
        List<ATAK_Project__c> atakProjects = new List<ATAK_Project__c>();
        for(ATAKProjectWrapper.Data projectData : projects.data) {
            ATAK_Project__c atakProject = createSingleATAKProject(projectData);
            atakProjects.add(atakProject);
        }

        Database.UpsertResult[] results = Database.upsert(atakProjects, ATAK_Project__c.Fields.SubProject_ATAK__c, false);
        Integer successCount = 0;
        Integer errorCount = 0;
        for(Database.UpsertResult result : results) {
            if(!result.isSuccess()) {
                for(Database.Error error : result.getErrors()) {
                    System.debug('Error: ' + error.getMessage());
                    errorCount++;
                }
            } else {
                successCount++;
            }
        }

        return 'Success: ' + successCount + ' Error: ' + errorCount + ' Total: ' + results.size() + ' processed.';

    }

    public static ATAK_Project__c createSingleATAKProject(ATAKProjectWrapper.Data projectData) {
        System.debug('ATAKProjectService.createATAKProject');
        System.debug('projectData: ' + projectData.projectcode);
        ATAK_Project__c atakProject = new ATAK_Project__c();
        atakProject.Subproject_Name__c = projectData.project_description;
        atakProject.SubProject_ATAK__c = projectData.projectcode;
        atakProject.Cost_centre_Atak_Id__c = projectData.costcenter_code;
        atakProject.Cost_centre_Atak_Name__c = projectData.costcenter_name;
        atakProject.Department_Code__c = projectData.department_code;
        atakProject.Department_Name__c = projectData.department_name;
        atakProject.Discipline__c = projectData.dim_discipline;
        atakProject.Language__c = projectData.dim_language;
        //atakProject.Region__c = projectData.dim_region; --> To be added once available in the JSON
        atakProject.Dossier__c = projectData.dossier;
        atakProject.Depot__c = projectData.depot_code;
        atakProject.Start_Date__c = projectData.project_startdate != '' && projectData.project_startdate != null ? Date.valueOf(projectData.project_startdate) : null;
        atakProject.End_Date__c = projectData.project_enddate != '' && projectData.project_enddate != null ? Date.valueOf(projectData.project_enddate) : null;
        atakProject.ATAK_Creation_Date__c = projectData.project_create_date != '' && projectData.project_create_date != null ? Date.valueOf(projectData.project_create_date) : null;

        for(ATAKProjectWrapper.Projectfunctionaris projectfunctionaris : projectData.projectfunctionaris) {
            if(projectfunctionaris.func_type == 'Werfleider') {
                atakProject.Site_Manager_Code__c = projectfunctionaris.func_initial;
                //atakProject.Owner = new User(ATAK_Code__c = projectfunctionaris.func_initial);
            }
        }

        System.debug('ATAKProjectService.createATAKProject - atakProject: ' + atakProject);

        return atakProject;
    }

}