force-app/main/default/objects/ATAK_Personnel__c/ATAK_Personnel__c.object-meta.xml
<CustomObject>
    <label>ATAK Personnel</label>
    <nameField>
        <label>ATAK Personnel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ATAK Personnel</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ATAK_Personnel__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATAK_Personnel__c/fields/Create_Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Create_Service_Resource__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Service Resource</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ATAK_Personnel__c/fields/Department_Name__c.field-meta.xml
<CustomField>
    <fullName>Department_Name__c</fullName>
    <label>Department Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ServiceResourceHandlerTest.cls
/**
 * Created by Frederik on 12/18/2024.
 */

@IsTest
private class ServiceResourceHandlerTest {
    @IsTest
    static void testCreateServiceResource() {

        ATAK_Personnel__c personnel = new ATAK_Personnel__c();
        personnel.Name = 'Test Name';
        personnel.Department_Name__c = 'Landscaping - Billing plan';
        personnel.Email__c = generateRandomEmail();
        personnel.First_Name__c = 'Karel';
        personnel.Last_Name__c = 'Krinkels';
        personnel.Phone__c = '0612345678';
        personnel.Code__c = '123qas';

        insert personnel;

        Test.startTest();
        personnel.Create_Service_Resource__c = true;
        update personnel;
        Test.stopTest();

    }

    private static string generateRandomEmail() {
        return 'test' + String.valueOf(Datetime.now().getTime()) + '@testkrinkels.com';
    }
}