force-app/main/default/objects/ATAK_Personnel__c/ATAK_Personnel__c.object-meta.xml
<CustomObject>
    <label>ATAK Personnel</label>
    <nameField>
        <label>ATAK Personnel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ATAK Personnel</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ATAK_Personnel__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATAK_Personnel__c/fields/Department_Code__c.field-meta.xml
<CustomField>
    <fullName>Department_Code__c</fullName>
    <label>Department Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATAK_Personnel__c/fields/Department_Name__c.field-meta.xml
<CustomField>
    <fullName>Department_Name__c</fullName>
    <label>Department Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATAK_Personnel__c/fields/Depot_Code__c.field-meta.xml
<CustomField>
    <fullName>Depot_Code__c</fullName>
    <label>Depot Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATAK_Personnel__c/fields/Depot_Name__c.field-meta.xml
<CustomField>
    <fullName>Depot_Name__c</fullName>
    <label>Depot Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATAK_Personnel__c/fields/Enddate__c.field-meta.xml
<CustomField>
    <fullName>Enddate__c</fullName>
    <label>Enddate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ATAK_Personnel__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATAK_Personnel__c/fields/Sitemanager_Code__c.field-meta.xml
<CustomField>
    <fullName>Sitemanager_Code__c</fullName>
    <label>Sitemanager Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATAK_Personnel__c/fields/Startdate__c.field-meta.xml
<CustomField>
    <fullName>Startdate__c</fullName>
    <label>Startdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ATAK_Personnel__c/fields/Statute__c.field-meta.xml
<CustomField>
    <fullName>Statute__c</fullName>
    <label>Statute</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ATAKPersonnelService.cls
/**
 * Created by fpardon on 12/11/2024.
 */

public with sharing class ATAKPersonnelService {

    public static String createATAKPersonnel(ATAKPersonnelWrapper personnel) {
        System.debug('ATAKPersonnelService.createATAKPersonnel');
        List<ATAK_Personnel__c> atakPersonnel = new List<ATAK_Personnel__c>();
        for(ATAKPersonnelWrapper.Data personnelData : personnel.data) {
            ATAK_Personnel__c atakPerson = createSingleATAKPersonnel(personnelData);
            atakPersonnel.add(atakPerson);
        }

        Database.UpsertResult[] results = Database.upsert(atakPersonnel, ATAK_Personnel__c.Fields.Code__c, false);
        Integer successCount = 0;
        Integer errorCount = 0;
        for(Database.UpsertResult result : results) {
            if(!result.isSuccess()) {
                for(Database.Error error : result.getErrors()) {
                    System.debug('Error: ' + error.getMessage());
                    errorCount++;
                }
            } else {
                successCount++;
            }
        }

        return 'Success: ' + successCount + ' Error: ' + errorCount + ' Total: ' + results.size() + ' processed.';

    }

    public static ATAK_Personnel__c createSingleATAKPersonnel(ATAKPersonnelWrapper.Data personnelData) {
        System.debug('ATAKPersonnelService.createATAKPersonnel');
        System.debug('personnelData: ' + personnelData.code);
        ATAK_Personnel__c atakPerson = new ATAK_Personnel__c();
        atakPerson.Code__c = personnelData.code;
        atakPerson.Name = personnelData.name;
        atakPerson.Phone__c = personnelData.phone;
        atakPerson.Mobile__c = personnelData.mobile;
        atakPerson.Email__c = personnelData.email;
        atakPerson.Depot_Code__c = personnelData.depot_code;
        atakPerson.Depot_Name__c = personnelData.depot_name;
        atakPerson.Department_Code__c = personnelData.department_code;
        atakPerson.Statute__c = personnelData.statute;
        atakPerson.Startdate__c = personnelData.startdate != '' ? Date.valueOf(personnelData.startdate) : null;
        atakPerson.Enddate__c = personnelData.enddate != '' ? Date.valueOf(personnelData.enddate) : null;
        atakPerson.Department_Name__c = personnelData.department_name;
        atakPerson.Sitemanager_Code__c = personnelData.sitemanager_code;
        atakPerson.Sitemanager_Code__c = personnelData.sitemanager_name;
        return atakPerson;
    }

}