force-app/main/default/objects/Asset/fields/Recurrence_Pattern__c.field-meta.xml
<CustomField>
    <fullName>Recurrence_Pattern__c</fullName>
    <label>Recurrence Pattern</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractLineItem/fields/Planning_Type__c.field-meta.xml
<CustomField>
    <fullName>Planning_Type__c</fullName>
    <label>Planning Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Work_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContractLineItem/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <label>Project Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContractLineItem/fields/Recurrence_Pattern__c.field-meta.xml
<CustomField>
    <fullName>Recurrence_Pattern__c</fullName>
    <label>Recurrence Pattern</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Work_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Preventive</fullName>
    </customValue>
    <customValue>
        <fullName>Curative</fullName>
    </customValue>
    <masterLabel>Work Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ServiceBuilderController.cls
/**
 * Created by Frederik on 5/31/2024.
 * Description:
 * Change Log:
 * Dependencies:
 */

public without sharing class ServiceBuilderController {
  @AuraEnabled
  public static List<ContractLineItem> getContractLines(String recordId) {
    List<ContractLineItem> contractLines = new List<ContractLineItem>();
    contractLines = [
      SELECT
        Id,
        LineItemNumber,
        ServiceContract.StartDate,
        ServiceContract.EndDate,
        Recurrence_Pattern__c,
        ServiceContractId,
        Product2Id,
        Product2.Name,
        AssetId,
        Asset.Name,
        StartDate,
        EndDate,
        PricebookEntryId,
        Quantity,
        UnitPrice,
        ListPrice,
        TotalPrice,
        Status,
        Planning_Type__c,
        Location__Street__s,
        Location__City__s,
        Location__PostalCode__s,
        Location__StateCode__s,
        Location__CountryCode__s,
        Project_Code__c
      FROM ContractLineItem
      WHERE ServiceContractId = :recordId
    ];
    return contractLines;
  }

  @AuraEnabled
  public static String getWrappedContractLines(String recordId) {
    List<ContractLineItem> contractLines = new List<ContractLineItem>();
    contractLines = [
      SELECT
        Id,
        LineItemNumber,
        ServiceContract.StartDate,
        ServiceContract.EndDate,
        Recurrence_Pattern__c,
        ServiceContractId,
        Product2Id,
        Product2.Name,
        AssetId,
        Asset.Name,
        StartDate,
        EndDate,
        PricebookEntryId,
        Quantity,
        UnitPrice,
        ListPrice,
        TotalPrice,
        Status,
        Planning_Type__c,
        Location__Street__s,
        Location__City__s,
        Location__PostalCode__s,
        Location__StateCode__s,
        Location__CountryCode__s,
        Project_Code__c
      FROM ContractLineItem
      WHERE ServiceContractId = :recordId
    ];
    ServiceBuilderWrapper wrapper = ServiceBuilderWrapper.wrapLineItems(
      contractLines
    );
    //Force the wrapper to be serialized as JSON
    System.debug('wrapper: ' + JSON.serialize(wrapper));
    return JSON.serialize(wrapper);
  }

  @AuraEnabled
  public static Boolean deleteContractLine(String contractLineId) {
    ContractLineItem contractLine = [
      SELECT Id
      FROM ContractLineItem
      WHERE Id = :contractLineId
      LIMIT 1
    ];
    try {
      delete contractLine;
      return true;
    } catch (Exception e) {
      return false;
    }
  }

  @AuraEnabled
  public static ContractLineItem saveContractLine(
    ContractLineItem contractLine
  ) {
    System.debug('contractLine: ' + contractLine);

    //Get the PricebookEntryId
    PricebookEntry pricebookEntry = [
      SELECT Id
      FROM PricebookEntry
      WHERE Product2Id = :contractLine.Product2Id
      LIMIT 1
    ];

    if (contractLine.Id == null) {
      contractLine.PricebookEntryId = pricebookEntry.Id;
      insert contractLine;
    } else {
      update contractLine;
    }

    return contractLine;
  }
}