force-app/main/default/objects/Account/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Depot KGC</fullName>
            </value>
            <value>
                <fullName>Waste Depot</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Type_of_Waste__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Waste__c</fullName>
    <label>Type of Waste</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Waste</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Depot_Visit_Planned__c.field-meta.xml
<CustomField>
    <fullName>Depot_Visit_Planned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Depot Visit Planned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Drop_Off_Items__c.field-meta.xml
<CustomField>
    <fullName>Drop_Off_Items__c</fullName>
    <label>Drop Off Items</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Pick_Up_Items__c.field-meta.xml
<CustomField>
    <fullName>Pick_Up_Items__c</fullName>
    <label>Pick Up Items</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Rework_for_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Rework_for_Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rework for Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Rework_Planned__c.field-meta.xml
<CustomField>
    <fullName>Rework_Planned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rework Planned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Rework_reasons__c.field-meta.xml
<CustomField>
    <fullName>Rework_reasons__c</fullName>
    <label>Rework reasons</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete work</fullName>
            </value>
            <value>
                <fullName>Quality issues</fullName>
            </value>
            <value>
                <fullName>Customer feedback</fullName>
            </value>
            <value>
                <fullName>Missed tasks</fullName>
            </value>
            <value>
                <fullName>Environmental conditions</fullName>
            </value>
            <value>
                <fullName>Material issues</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Waste_to_Drop_Off__c.field-meta.xml
<CustomField>
    <fullName>Waste_to_Drop_Off__c</fullName>
    <label>Waste to Drop Off</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Waste</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Waste_Visit_Planned__c.field-meta.xml
<CustomField>
    <fullName>Waste_Visit_Planned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Waste Visit Planned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Work_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Type__c</fullName>
    <label>Work Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
                <default>true</default>
                <label>Production</label>
            </value>
            <value>
                <fullName>Shop Visit</fullName>
            </value>
            <value>
                <fullName>Depot Visit</fullName>
            </value>
            <value>
                <fullName>Waste Depot Visit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Type_of_Waste.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Asbestos</fullName>
    </customValue>
    <customValue>
        <fullName>Asphalt</fullName>
    </customValue>
    <customValue>
        <fullName>Class II waste</fullName>
    </customValue>
    <customValue>
        <fullName>Concrete debris</fullName>
    </customValue>
    <customValue>
        <fullName>Construction debris</fullName>
    </customValue>
    <customValue>
        <fullName>Green waste</fullName>
    </customValue>
    <customValue>
        <fullName>Mowing waste</fullName>
    </customValue>
    <customValue>
        <fullName>Sludge</fullName>
    </customValue>
    <customValue>
        <fullName>Soil</fullName>
    </customValue>
    <customValue>
        <fullName>Sweeping waste</fullName>
    </customValue>
    <customValue>
        <fullName>Tree trunks and roots</fullName>
    </customValue>
    <customValue>
        <fullName>Type B wood</fullName>
    </customValue>
    <customValue>
        <fullName>Tyres</fullName>
    </customValue>
    <customValue>
        <fullName>Wood chips</fullName>
    </customValue>
    <masterLabel>Type of Waste</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SFS_WorkOrderCreatorController.cls
/**
 * Created by fpardon on 11/12/2024.
 */

public with sharing class SFS_WorkOrderCreatorController {

    @AuraEnabled
    public static List<String> getWasteTypePicklist() {


        try {
            Schema.DescribeFieldResult fieldResult = Account.Type_of_Waste__c.getDescribe();
            List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
            List<String> options = new List<String>();

            for (Schema.PicklistEntry entry : picklistValues) {
                if (entry.isActive()) {
                    options.add(entry.getValue());
                }
            }
            System.debug('options: ' + options);
            return options;
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Account> getWasteDepots(List<String> wasteTypes) {
        try {
            String wasteTypesQuery = '';
            for(String wasteType : wasteTypes) {
                if(wasteTypesQuery != '') {
                    wasteTypesQuery += ' OR ';
                }
                wasteTypesQuery += 'Type_of_Waste__c INCLUDES (\'' + String.escapeSingleQuotes(wasteType) + '\')';
            }

            String query = 'SELECT Id, Name, Contract__c, Type_of_Waste__c, ' +
                    'ShippingPostalCode, ShippingCity ' +
                    'FROM Account ' +
                    'WHERE (' + wasteTypesQuery + ') ' +
                    'WITH SECURITY_ENFORCED ' +
                    'LIMIT 50';

            System.debug('Query: ' + query);
            return Database.query(query);
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Id createWasteVisitWorkOrder(Id parentRecordId, Id depotId, String wasteTypes) {

        System.debug('parentRecordId: ' + parentRecordId);
        System.debug('depotId: ' + depotId);
        System.debug('wasteTypes: ' + wasteTypes);

        try {

            //Get the WorkOrder from the ServiceAppointment
            ServiceAppointment serviceAppointment = [
                    SELECT Id, ParentRecordId
                    FROM ServiceAppointment
                    WHERE Id = :parentRecordId
                    WITH SECURITY_ENFORCED
                    LIMIT 1
            ];


            // Get the parent work order info
            WorkOrder parentWO = [
                    SELECT Id, MaintenancePlanId, ServiceTerritoryId,
                            AssetId, SuggestedMaintenanceDate, StartDate, EndDate
                    FROM WorkOrder
                    WHERE Id = :serviceAppointment.ParentRecordId
                    WITH SECURITY_ENFORCED
                    LIMIT 1
            ];

            System.debug('parentWO: ' + parentWO);

            // Get the work type
            WorkType wasteManagementWT = [
                    SELECT Id
                    FROM WorkType
                    WHERE Name = 'Waste Management'
                    WITH SECURITY_ENFORCED
                    LIMIT 1
            ];

            System.debug('wasteManagementWT: ' + wasteManagementWT);

            // Create the waste visit work order
            WorkOrder wo = new WorkOrder(
                    ParentWorkOrderId = parentWO.Id,
                    AccountId = depotId,
                    MaintenancePlanId = parentWO.MaintenancePlanId,
                    Subject = 'Waste Depot Visit',
                    ServiceTerritoryId = parentWO.ServiceTerritoryId,
                    WorkTypeId = wasteManagementWT.Id,
                    AssetId = parentWO.AssetId,
                    Waste_Visit_Planned__c = true,
                    Waste_to_Drop_Off__c = wasteTypes,
                    Work_Order_Type__c = 'Waste Depot Visit',
                    SuggestedMaintenanceDate = parentWO.SuggestedMaintenanceDate,
                    StartDate = parentWO.StartDate,
                    EndDate = parentWO.EndDate
            );

            insert wo;
            return wo.Id;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Account> getDepots() {
        try {
            return [
                    SELECT Id, Name
                    FROM Account
                    WHERE Sub_Type__c = 'Depot KGC'
                    WITH SECURITY_ENFORCED
                    ORDER BY Name
                    LIMIT 100
            ];
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Id createDepotVisitWorkOrder(
            Id parentRecordId,
            Id depotId,
            String subject,
            String dropOffItems,
            String pickUpItems
    ) {
        System.debug('parentRecordId: ' + parentRecordId);
        System.debug('depotId: ' + depotId);
        System.debug('subject: ' + subject);
        System.debug('dropOffItems: ' + dropOffItems);
        System.debug('pickUpItems: ' + pickUpItems);

        try {
            //Get the WorkOrder from the ServiceAppointment
            ServiceAppointment serviceAppointment = [
                    SELECT Id, ParentRecordId
                    FROM ServiceAppointment
                    WHERE Id = :parentRecordId
                    WITH SECURITY_ENFORCED
                    LIMIT 1
            ];

            // Get the parent work order info
            WorkOrder parentWO = [
                    SELECT Id, MaintenancePlanId, ServiceTerritoryId,
                            ServiceContractId, AssetId, SuggestedMaintenanceDate, StartDate, EndDate
                    FROM WorkOrder
                    WHERE Id = :serviceAppointment.ParentRecordId
                    WITH SECURITY_ENFORCED
                    LIMIT 1
            ];

            System.debug('parentWO: ' + parentWO);

            // Get the work type
            WorkType depotWT = [
                    SELECT Id
                    FROM WorkType
                    WHERE Name = 'Internal Depot'
                    WITH SECURITY_ENFORCED
                    LIMIT 1
            ];

            System.debug('depotWT: ' + depotWT);

            // Create depot visit work order
            WorkOrder wo = new WorkOrder(
                    ParentWorkOrderId = parentWO.Id,
                    AccountId = depotId,
                    MaintenancePlanId = parentWO.MaintenancePlanId,
                    Subject = subject,
                    ServiceTerritoryId = parentWO.ServiceTerritoryId,
                    ServiceContractId = parentWO.ServiceContractId,
                    WorkTypeId = depotWT.Id,
                    AssetId = parentWO.AssetId,
                    Depot_Visit_Planned__c = true,
                    Drop_Off_Items__c = dropOffItems,
                    Pick_Up_Items__c = pickUpItems,
                    Work_Order_Type__c = 'Depot Visit',
                    SuggestedMaintenanceDate = parentWO.SuggestedMaintenanceDate,
                    StartDate = parentWO.StartDate,
                    EndDate = parentWO.EndDate
            );

            insert wo;
            return wo.Id;
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static ServiceAppointment getServiceAppointments(String appointmentId) {
        return [
                SELECT
                        Id,
                        AppointmentNumber,
                        Status,
                        SchedStartTime,
                        SchedEndTime,
                        ParentRecordId,
                        ParentRecordType,
                        TYPEOF ParentRecord
                                WHEN WorkOrder THEN
                                Id,
                                Subject,
                                Description,
                                Priority,
                                Status,
                                ServiceTerritoryId,
                                Duration,
                                DurationType,
                                AccountId,
                                Account.Name
                        END
                FROM ServiceAppointment
                WHERE Id = :appointmentId
                WITH SECURITY_ENFORCED
                LIMIT 1
        ];
    }

    @AuraEnabled
    public static List<String> getReworkReasons() {
        try {
            Schema.DescribeFieldResult fieldResult = WorkOrder.Rework_reasons__c.getDescribe();
            List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
            List<String> options = new List<String>();

            for (Schema.PicklistEntry entry : picklistValues) {
                if (entry.isActive()) {
                    options.add(entry.getValue());
                }
            }
            return options;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static WorkOrder getExistingTasks(Id serviceAppointmentId) {

        try {

            ServiceAppointment serviceAppointment = [
                    SELECT Id, ParentRecordId
                    FROM ServiceAppointment
                    WHERE Id = :serviceAppointmentId
                    WITH SECURITY_ENFORCED
                    LIMIT 1
            ];

            return [
                    SELECT Id, WorkOrderNumber,
                    (SELECT Id, Description
                    FROM WorkOrderLineItems
                    ORDER BY CreatedDate ASC)
                    FROM WorkOrder
                    WHERE Id = :serviceAppointment.ParentRecordId
                    WITH SECURITY_ENFORCED
                    LIMIT 1
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Id createReworkOrder(
            Id parentRecordId,
            String subject,
            String reworkReason,
            List<Id> selectedTaskIds,
            List<String> newTasks
    ) {
        try {
            //Get the WorkOrder from the ServiceAppointment
            ServiceAppointment serviceAppointment = [
                    SELECT Id, ParentRecordId
                    FROM ServiceAppointment
                    WHERE Id = :parentRecordId
                    WITH SECURITY_ENFORCED
                    LIMIT 1
            ];

            // Get parent work order info
            WorkOrder parentWO = [
                    SELECT Id, AccountId, AssetId, MaintenancePlanId,
                            ServiceContractId, ServiceTerritoryId, WorkOrderNumber, SuggestedMaintenanceDate, StartDate, EndDate
                    FROM WorkOrder
                    WHERE Id = :serviceAppointment.ParentRecordId
                    WITH SECURITY_ENFORCED
                    LIMIT 1
            ];

            // Get work type
            WorkType reworkWT = [
                    SELECT Id
                    FROM WorkType
                    WHERE Name = 'Rework'
                    WITH SECURITY_ENFORCED
                    LIMIT 1
            ];

            // Create rework order
            WorkOrder wo = new WorkOrder(
                    ParentWorkOrderId = parentWO.Id,
                    AccountId = parentWO.AccountId,
                    AssetId = parentWO.AssetId,
                    MaintenancePlanId = parentWO.MaintenancePlanId,
                    ServiceContractId = parentWO.ServiceContractId,
                    ServiceTerritoryId = parentWO.ServiceTerritoryId,
                    Subject = subject,
                    WorkTypeId = reworkWT.Id,
                    Rework_Planned__c = true,
                    Rework_reasons__c = reworkReason,
                    Rework_for_Work_Order__c = parentWO.Id,
                    SuggestedMaintenanceDate = parentWO.SuggestedMaintenanceDate,
                    StartDate = parentWO.StartDate,
                    EndDate = parentWO.EndDate
            );

            insert wo;

            List<WorkOrderLineItem> linesToInsert = new List<WorkOrderLineItem>();

            // Add selected existing tasks
            if (!selectedTaskIds.isEmpty()) {
                for (WorkOrderLineItem existingLine : [
                        SELECT Description
                        FROM WorkOrderLineItem
                        WHERE Id IN :selectedTaskIds
                        WITH SECURITY_ENFORCED
                ]) {
                    linesToInsert.add(new WorkOrderLineItem(
                            WorkOrderId = wo.Id,
                            Description = existingLine.Description,
                            Status = 'New'
                    ));
                }
            }

            // Add new tasks
            if (!newTasks.isEmpty()) {
                for (String taskDescription : newTasks) {
                    linesToInsert.add(new WorkOrderLineItem(
                            WorkOrderId = wo.Id,
                            Description = taskDescription,
                            Status = 'New'
                    ));
                }
            }

            if (!linesToInsert.isEmpty()) {
                insert linesToInsert;
            }

            return wo.Id;
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }

}