force-app/main/default/objects/Account/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Depot KGC</fullName>
            </value>
            <value>
                <fullName>Waste Depot</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Type_of_Waste__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Waste__c</fullName>
    <label>Type of Waste</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Waste</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Type_of_Waste.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Asbestos</fullName>
    </customValue>
    <customValue>
        <fullName>Asphalt</fullName>
    </customValue>
    <customValue>
        <fullName>Class II waste</fullName>
    </customValue>
    <customValue>
        <fullName>Concrete debris</fullName>
    </customValue>
    <customValue>
        <fullName>Construction debris</fullName>
    </customValue>
    <customValue>
        <fullName>Green waste</fullName>
    </customValue>
    <customValue>
        <fullName>Mowing waste</fullName>
    </customValue>
    <customValue>
        <fullName>Sludge</fullName>
    </customValue>
    <customValue>
        <fullName>Soil</fullName>
    </customValue>
    <customValue>
        <fullName>Sweeping waste</fullName>
    </customValue>
    <customValue>
        <fullName>Tree trunks and roots</fullName>
    </customValue>
    <customValue>
        <fullName>Type B wood</fullName>
    </customValue>
    <customValue>
        <fullName>Tyres</fullName>
    </customValue>
    <customValue>
        <fullName>Wood chips</fullName>
    </customValue>
    <masterLabel>Type of Waste</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountWasteRetriever.cls
public with sharing class AccountWasteRetriever {
    @InvocableMethod(label='Retrieve Accounts by Waste Types' description='Fetch accounts matching all selected waste types')
    public static List<List<Account>> getAccountsByWasteTypes(List<RequestWrapper> requests) {
        // Initialize an empty list to hold accounts
        List<Account> accounts = new List<Account>();
        
        // Loop through the requests (usually one in this case)
        for (RequestWrapper request : requests) {
            if (request.wasteTypes != null && !request.wasteTypes.isEmpty()) {
                // Dynamic SOQL to find accounts that match ALL selected waste types
                String query = 'SELECT Id, Name, Type_of_Waste__c, Contract__c, ShippingCity, ShippingPostalCode ' +
                               'FROM Account ' +
                               'WHERE Sub_Type__c = \'Waste Depot\'';
                
                // Add conditions to include each waste type
                for (Integer i = 0; i < request.wasteTypes.size(); i++) {
                    query += ' AND Type_of_Waste__c INCLUDES (\'' + request.wasteTypes[i] + '\')';
                }
                
                // Execute the query and cast the result to List<Account>
                accounts.addAll((List<Account>)Database.query(query));
            }
        }
        
        // Return the accounts as a collection
        return new List<List<Account>>{accounts};
    }
    
    // Wrapper class for input variables
    public class RequestWrapper {
        @InvocableVariable(required=true description='List of selected waste types')
        public List<String> wasteTypes;
    }
}