force-app/main/default/objects/SD_Import__c/SD_Import__c.object-meta.xml
<CustomObject>
    <label>SD Import</label>
    <nameField>
        <displayFormat>SDI-{000000}</displayFormat>
        <label>SD Import</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SD Import</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SD_Import__c/fields/AfwezigheidDagdeelKode__c.field-meta.xml
<CustomField>
    <fullName>AfwezigheidDagdeelKode__c</fullName>
    <label>AfwezigheidDagdeelKode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SD_Import__c/fields/AfwezigheidPresturen__c.field-meta.xml
<CustomField>
    <fullName>AfwezigheidPresturen__c</fullName>
    <label>AfwezigheidPresturen</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SD_Import__c/fields/AfwezigheidscodelabelCode__c.field-meta.xml
<CustomField>
    <fullName>AfwezigheidscodelabelCode__c</fullName>
    <label>AfwezigheidscodelabelCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SD_Import__c/fields/ArbeidsContractWerknemer__c.field-meta.xml
<CustomField>
    <fullName>ArbeidsContractWerknemer__c</fullName>
    <label>ArbeidsContractWerknemer</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SD_Import__c/fields/KalenderdagDat__c.field-meta.xml
<CustomField>
    <fullName>KalenderdagDat__c</fullName>
    <label>KalenderdagDat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SD_Import__c/fields/PersoonId__c.field-meta.xml
<CustomField>
    <fullName>PersoonId__c</fullName>
    <label>PersoonId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SDWorxAbsenceBatch.cls
/**
* Created by Frederik on 11/15/2024.
* Description:
* Change Log:
* Dependencies:
*/

public class SDWorxAbsenceBatch implements Database.Batchable<sObject>, Schedulable {

    public void execute(SchedulableContext sc) {
        Database.executeBatch(this);
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        // Query for SD_Import__c records that need to be processed
        // You might want to add additional filtering criteria
        return Database.getQueryLocator([
                SELECT Id, ArbeidsContractWerknemer__c, KalenderdagDat__c,
                        AfwezigheidDagdeelKode__c, AfwezigheidPresturen__c,
                        PersoonId__c, AfwezigheidscodelabelCode__c
                FROM SD_Import__c
        ]);
    }

    public void execute(Database.BatchableContext bc, List<SD_Import__c> scope) {
        try {
            // Process the records
            SDWorxToResourceAbsenceService.createAbsenceRecords(scope);

            // Mark records as processed
            delete scope;

        } catch(Exception e) {
            System.debug('Error processing batch: ' + e.getMessage());
        }
    }

    public void finish(Database.BatchableContext bc) {
        // Any post-processing logic can go here
        System.debug('Batch job completed');
    }

    // Method to schedule the batch job
    public static String scheduleJob(String jobName, String cronExp) {
        return System.schedule(jobName, cronExp, new SDWorxAbsenceBatch());
    }
}