force-app/main/default/objects/Logger_Settings__c/fields/Enable_Outbound_Logs__c.field-meta.xml
<CustomField>
    <fullName>Enable_Outbound_Logs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Outbound Logs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Outbound_Log__c/Outbound_Log__c.object-meta.xml
<CustomObject>
    <label>Outbound Log</label>
    <nameField>
        <displayFormat>OL-{000000}</displayFormat>
        <label>Outbound Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Outbound_Log__c/fields/JSON_Body__c.field-meta.xml
<CustomField>
    <fullName>JSON_Body__c</fullName>
    <label>JSON Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/OutboundLoggerService.cls
/**
 * Created by fpardon on 18/11/2024.
 */

public with sharing class OutboundLoggerService {

    // Static variable to cache the logging enabled setting
    private static Boolean isLoggingEnabled;

    // Getter method to check if logging is enabled
    public static Boolean getIsLoggingEnabled() {
        if (isLoggingEnabled == null) {
            // Get the custom setting for the current user context
            Logger_Settings__c settings = Logger_Settings__c.getInstance();
            isLoggingEnabled = settings != null ? settings.Enable_Outbound_Logs__c : false;
        }
        return isLoggingEnabled;
    }

    public static void createOutboundLog(String messageBody, String messageError) {
        if (getIsLoggingEnabled()) {
            try {
                // Create a new Inbound Log record
                Outbound_Log__c log = new Outbound_Log__c();
                log.JSON_Body__c = messageBody;
                log.Error_Message__c = messageError;
                insert log;
            } catch (Exception e) {
                // Log the exception
                System.debug('Error creating inbound log: ' + e.getMessage());
            }
        }
    }

}