force-app/main/default/objects/Contact/fields/Language_Formula__c.field-meta.xml
<CustomField>
    <fullName>Language_Formula__c</fullName>
    <formula>CASE(TEXT( Language__c ), 
&quot;Dutch&quot;, &quot;nl&quot;, 
&quot;French&quot;, &quot;fr&quot;,
&quot;en&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Language Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SD_Import__c/SD_Import__c.object-meta.xml
<CustomObject>
    <label>SD Import</label>
    <nameField>
        <displayFormat>SDI-{000000}</displayFormat>
        <label>SD Import</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SD Import</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder/fields/PDF_Status__c.field-meta.xml
<CustomField>
    <fullName>PDF_Status__c</fullName>
    <label>PDF Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Review Needed</fullName>
            </value>
            <value>
                <fullName>Ready to be Generated</fullName>
                <default>true</default>
                <label>Ready to be Generated</label>
            </value>
            <value>
                <fullName>Ready to be Sent</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Not Generated - No Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ServiceReportGenerationBatch.cls
/**
* Created by Frederik on 1/7/2025.
* Description:
* Change Log:
* Dependencies:
*/

public without sharing class ServiceReportGenerationBatch implements Database.Batchable<sObject>, Schedulable, Database.AllowsCallouts {

    public void execute(SchedulableContext sc) {
        Database.executeBatch(this);
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        // Query for SD_Import__c records that need to be processed
        // You might want to add additional filtering criteria
        return Database.getQueryLocator([
                SELECT Id, Contact.Language_Formula__c FROM WorkOrder WHERE PDF_Status__c = 'Ready to be Generated' AND Status = 'Completed' AND ContactId != null
        ]);
    }

    public void execute(Database.BatchableContext bc, List<WorkOrder> scope) {
        try {

            cadmus_core__Doc_Config__c docConfig = [SELECT Id FROM cadmus_core__Doc_Config__c WHERE Name = 'Generate Service Report'];

            for(WorkOrder wo : scope) {
                System.debug('Processing WorkOrder: ' + wo.Id);
                System.debug('Language: ' + wo.Contact.Language_Formula__c);
                PDFButler_ConvertService.createServiceReport(wo.Id, docConfig.Id, wo.Contact.Language_Formula__c);
            }

        } catch(Exception e) {
            System.debug('Error processing batch: ' + e.getMessage());
        }
    }

    public void finish(Database.BatchableContext bc) {
        // Any post-processing logic can go here
        System.debug('Batch job completed');
        List<WorkOrder> workOrders = [SELECT Id, ContactId FROM WorkOrder WHERE PDF_Status__c = 'Ready to be Generated' AND Status = 'Completed' AND ContactId = null];
        for(WorkOrder wo : workOrders) {
            wo.PDF_Status__c = 'Not Generated - No Contact';
        }
        update workOrders;
    }
}